# Use root/example as user/password credentials
version: "3.1"

services:
  clemento:
    build:
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4241:4241"
    volumes:
      - .:/app:cached
    entrypoint: /app/entrypoint.sh


